### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by boluomeng** [tigerandy163com/DownLoadManager#1]
楼主的项目非常不错，赞一个，希望以后能继续维护下去，做成一个优秀的文件下载类工具。
使用后也感觉到有些可以提升的地方，比如将除ASIHTTP外的代码转换为ARC、继续提升稳定性，在使用过程中还是出现了奔溃的情况(数组越界)。

**Comment by EarthMass** [comment]
为什么不把数据管理建一个数据库管理呢
