### ISSUE TITLE
下载200M左右的文件时出现下载中progress计算突然翻倍的现象，请问大神有没有什么好的解决方案？

### ISSUE THREAD

**Issue by leeysun** [tigerandy163com/DownLoadManager#2]
这种情况一般出现在home键退出后按锁屏，然后再打开软件就会出现这种情况，恢复下载时
-(void)request:(MidHttpRequest *)request didReceiveBytes:(long long)bytes;
这个代理请求的bytes数据为之前下载的全部数据

**Comment by tigerandy163com** [comment]
改变了isFirstReceived 这个标志的赋值位置，在收到Response时进行。
